[package]
name = "grav_body_sim_bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.0", features = ["bevy_dev_tools", "bevy_feathers"] }
bevy_egui = "0.40.1"
bevy_panorbit_camera = { path = "/Users/zaidzamani/Desktop/Projects/other_ppl_projects/bevy_panorbit_camera", version = "0.35.0", features = ["bevy_egui"] }
rand = "0.10.2"
